---
- name: deployment
  hosts: 54.252.187.173
  become: true
  vars:
    nexus_url: http://ec2-52-65-162-201.ap-southeast-2.compute.amazonaws.com:8081/repository
    repository_type: java-maven-war-app-release
    group_id: com%2Fmycompany%2Fapp
    artifact_id: hello-world-war
    version: 2.0.0
    build_number: "{{ build_number }}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{ nexus_url }}/{{ repository_type }}/{{ group_id }}%2F{{ artifact_id }}%2F{{ version }}-{{ build_number }}%2F{{ artifact_id }}-{{ version }}-{{ build_number }}.war"
      dest: /home/ec2-user/hello-world-war-{{ version }}-{{ build_number }}.war
      username: admin
      password: admin

  - name: Check if the war file exists
    ansible.builtin.stat:
      path: /home/ec2-user/hello-world-war-{{ version }}-{{ build_number }}.war
    register: war_file

  - name: Debug war file stats
    ansible.builtin.debug:
      var: war_file

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/hello-world-war-{{ version }}-{{ build_number }}.war /home/ec2-user/nisha.war
    when: war_file.stat.exists

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/nisha.war /opt/apache-tomcat-9.0.90/webapps/nisha.war
    when: war_file.stat.exists

  - name: remove the artifact
    ansible.builtin.shell: rm -rf /home/ec2-user/nisha.war
    when: war_file.stat.exists

